apiVersion: spark.apache.org/v1alpha1
kind: SparkApplication
metadata:
  name: spark-app
spec:
  mainClass: "com.bulatmain.App"
  jars: "local:///app/classpath/spark-app-1.0.0-SNAPSHOT.jar"
  sparkConf:
    spark.app.name: "spark-app"
    spark.jars.ivy: "/tmp/ivy"
    spark.dynamicAllocation.enabled: "true"
    spark.dynamicAllocation.shuffleTracking.enabled: "true"
    spark.dynamicAllocation.maxExecutors: "3"
    spark.kubernetes.authenticate.driver.serviceAccountName: "spark"
    spark.kubernetes.container.image: "bulatmain/spark-app:1.0.0-SNAPSHOT"
  applicationTolerations:
    resourceRetainPolicy: OnFailure
  runtimeVersions:
    sparkVersion: "3.5.5"