apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  namespace: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: bulatmain/shop-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "admin123"
        - name: POSTGRES_DB
          value: "db"
        resources:
              requests:
                memory: "128Mi"
                cpu: "125m"
              limits:
                memory: "256Mi"
                cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-app-service
  namespace: db
spec:
  selector:
    app: shop-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP