apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: bulatmain/shop-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: shop-app-secret
              key: PG_USERNAME
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shop-app-secret
              key: PG_PASSWORD
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              name: shop-app-config
              key: PG_HOST
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              name: shop-app-config
              key: PG_PORT
        - name: PG_DB
          valueFrom:
            configMapKeyRef:
              name: shop-app-config
              key: PG_DB
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: shop-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: shop-app-config
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: shop-app-config
              key: REDIS_DB
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        volumeMounts:
        - name: log-storage
          mountPath: /app/logs
      volumes:
      - name: log-storage
        persistentVolumeClaim:
          claimName: shop-app-log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: shop-app-service
spec:
  selector:
    app: shop-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: shop-app-secret
  namespace: db
type: Opaque
stringData:
  PG_USERNAME: postgres
  PG_PASSWORD: admin123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-app-config
  namespace: db
data:
  PG_HOST: postgres-headless
  PG_PORT: "5432"
  PG_DB: db
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shop-app-log-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard